# War and conflict

In [1]:
import polars as pl

# cfg = pl.Config()
# cfg.set_tbl_rows(30)
# cfg.set_fmt_str_lengths(1000)

## Get data

In [2]:
df = pl.read_parquet('../data/facts/FIN*.parquet')

In [3]:
df.schema

Schema([('entity_word_id', String),
        ('speech_id', String),
        ('paragraph_id', String),
        ('sentence_id', String),
        ('sentence_content_current', String),
        ('sentence_content_previous', String),
        ('sentence_content_next', String),
        ('sentence_sentiment_value', Float32),
        ('sentence_sentiment_ana', String),
        ('total_tokens_in_speech', Int32),
        ('total_tokens_in_session', Int32),
        ('entity_category', String),
        ('entity_content', String),
        ('country', String),
        ('session_date', Date),
        ('debate_topic', String),
        ('speaker_id', String),
        ('speaker_ana', String)])

In [4]:
# Number of rows
df.height

464872

In [5]:
# Annotate session year
df = df.with_columns(pl.col('session_date').dt.year().alias('session_year'))

# Number of rows per year
df.group_by('session_year').agg(pl.len().alias('nb_rows_per_year')).sort('session_year')

shape: (8, 2)
┌──────────────┬──────────────────┐
│ session_year ┆ nb_rows_per_year │
│ ---          ┆ ---              │
│ i32          ┆ u32              │
╞══════════════╪══════════════════╡
│ 2015         ┆ 42475            │
│ 2016         ┆ 77542            │
│ 2017         ┆ 74275            │
│ 2018         ┆ 65414            │
│ 2019         ┆ 60363            │
│ 2020         ┆ 77986            │
│ 2021         ┆ 66182            │
│ 2022         ┆ 635              │
└──────────────┴──────────────────┘

In [6]:
# Number of rows per debate topic
df.group_by('debate_topic').agg(pl.len().alias('nb_rows_per_topic')).sort(
    'debate_topic'
)

shape: (23, 2)
┌──────────────┬───────────────────┐
│ debate_topic ┆ nb_rows_per_topic │
│ ---          ┆ ---               │
│ str          ┆ u32               │
╞══════════════╪═══════════════════╡
│ argic        ┆ 15570             │
│ civil        ┆ 18286             │
│ cultu        ┆ 2095              │
│ defen        ┆ 18993             │
│ domes        ┆ 10866             │
│ …            ┆ …                 │
│ other        ┆ 32095             │
│ techn        ┆ 6730              │
│ trade        ┆ 3897              │
│ trans        ┆ 23635             │
│ welfa        ┆ 17729             │
└──────────────┴───────────────────┘

## Filter data

In [7]:
def get_results(filtered_df):
    return (
        filtered_df.with_columns(
            pl.struct(
                [
                    pl.col('session_year'),
                    pl.col('debate_topic'),
                    pl.col('sentence_sentiment_value'),
                    pl.col('sentence_sentiment_ana'),
                    (
                        pl.col('sentence_content_previous').fill_null('')
                        + ' '
                        + pl.col('sentence_content_current')
                        + ' '
                        + pl.col('sentence_content_next').fill_null('')
                    ).str.strip_chars(),
                ]
            ).alias('sentence_with_context')
        )
        .sort('session_year')
        .group_by([pl.col('entity_category'), pl.col('entity_content')])
        .agg(pl.col('sentence_with_context').alias('sentences_with_context'))
        .with_columns(pl.col('sentences_with_context').list.len().alias('nb_sentences'))
        .sort('nb_sentences', descending=True)
    )

### Keywords

In [8]:
# Look for a particular keyword in "sentence_content_current"
def search_keyword(keyword):
    pattern = rf'(?i){keyword}'
    return get_results(
        df.filter(
            pl.col('entity_category').is_in(['LOC']),
            pl.col('sentence_content_current').str.contains(pattern),
        )
    )

In [9]:
# Mentions of "war"
search_keyword(r'\bwar\b')

shape: (173, 4)
┌─────────────────┬─────────────────┬─────────────────────────────────┬──────────────┐
│ entity_category ┆ entity_content  ┆ sentences_with_context          ┆ nb_sentences │
│ ---             ┆ ---             ┆ ---                             ┆ ---          │
│ str             ┆ str             ┆ list[struct[5]]                 ┆ u32          │
╞═════════════════╪═════════════════╪═════════════════════════════════╪══════════════╡
│ LOC             ┆ Finland         ┆ [{2015,"inter",1.367,"senti:mi… ┆ 249          │
│ LOC             ┆ Europe          ┆ [{2015,"inter",1.544,"senti:ne… ┆ 62           │
│ LOC             ┆ Russia          ┆ [{2015,"inter",0.131,"senti:ne… ┆ 35           │
│ LOC             ┆ Syria           ┆ [{2015,"inter",2.004,"senti:ne… ┆ 33           │
│ LOC             ┆ Ukraine         ┆ [{2015,"inter",4.24,"senti:mix… ┆ 27           │
│ …               ┆ …               ┆ …                               ┆ …            │
│ LOC             ┆ Jordan          ┆ [{2016,"immig",0.412,"senti:ne… ┆ 1            │
│ LOC             ┆ Kalevala        ┆ [{2015,"lands",3.72,"senti:mix… ┆ 1            │
│ LOC             ┆ Karabakh        ┆ [{2020,"inter",0.027,"senti:ne… ┆ 1            │
│ LOC             ┆ Hippocrates     ┆ [{2015,"healt",2.398,"senti:ne… ┆ 1            │
│ LOC             ┆ Western Ukraine ┆ [{2015,"immig",2.767,"senti:ne… ┆ 1            │
└─────────────────┴─────────────────┴─────────────────────────────────┴──────────────┘

In [10]:
# Mentions of "conflict"
search_keyword('conflict')

shape: (100, 4)
┌─────────────────┬────────────────┬─────────────────────────────────┬──────────────┐
│ entity_category ┆ entity_content ┆ sentences_with_context          ┆ nb_sentences │
│ ---             ┆ ---            ┆ ---                             ┆ ---          │
│ str             ┆ str            ┆ list[struct[5]]                 ┆ u32          │
╞═════════════════╪════════════════╪═════════════════════════════════╪══════════════╡
│ LOC             ┆ Finland        ┆ [{2015,"civil",1.581,"senti:ne… ┆ 221          │
│ LOC             ┆ Europe         ┆ [{2015,"inter",1.426,"senti:mi… ┆ 32           │
│ LOC             ┆ Iraq           ┆ [{2015,"immig",3.965,"senti:mi… ┆ 24           │
│ LOC             ┆ Ukraine        ┆ [{2015,"inter",1.626,"senti:ne… ┆ 22           │
│ LOC             ┆ Syria          ┆ [{2015,"immig",3.965,"senti:mi… ┆ 22           │
│ …               ┆ …              ┆ …                               ┆ …            │
│ LOC             ┆ Northern Iraq  ┆ [{2021,"inter",-0.026,"senti:n… ┆ 1            │
│ LOC             ┆ Nordea Capital ┆ [{2015,"gover",2.275,"senti:ne… ┆ 1            │
│ LOC             ┆ Hungary        ┆ [{2016,"inter",0.97,"senti:mix… ┆ 1            │
│ LOC             ┆ East Ukraine   ┆ [{2021,"inter",0.109,"senti:ne… ┆ 1            │
│ LOC             ┆ Balkans        ┆ [{2017,"inter",0.763,"senti:mi… ┆ 1            │
└─────────────────┴────────────────┴─────────────────────────────────┴──────────────┘

### Entities

In [11]:
# Look for a particular entity in "entity_content"
def search_entity(entity):
    pattern = rf'(?i){entity}'
    return get_results(df.filter(pl.col('entity_content').str.contains(pattern)))

In [12]:
# Mentions of "ukrain"
search_entity('ukrain')

shape: (9, 4)
┌─────────────────┬────────────────────────┬─────────────────────────────────┬──────────────┐
│ entity_category ┆ entity_content         ┆ sentences_with_context          ┆ nb_sentences │
│ ---             ┆ ---                    ┆ ---                             ┆ ---          │
│ str             ┆ str                    ┆ list[struct[5]]                 ┆ u32          │
╞═════════════════╪════════════════════════╪═════════════════════════════════╪══════════════╡
│ LOC             ┆ Ukraine                ┆ [{2015,"civil",2.727,"senti:ne… ┆ 441          │
│ LOC             ┆ Eastern Ukraine        ┆ [{2015,"inter",0.169,"senti:ne… ┆ 64           │
│ MISC            ┆ Ukrainian              ┆ [{2015,"civil",2.79,"senti:neu… ┆ 38           │
│ MISC            ┆ Ukrainians             ┆ [{2015,"immig",2.638,"senti:ne… ┆ 11           │
│ LOC             ┆ East Ukraine           ┆ [{2018,"inter",0.043,"senti:ne… ┆ 2            │
│ MISC            ┆ Ukraine War            ┆ [{2015,"inter",0.594,"senti:mi… ┆ 1            │
│ LOC             ┆ Richard Sakwan Ukraine ┆ [{2017,"inter",3.537,"senti:mi… ┆ 1            │
│ LOC             ┆ Western Ukraine        ┆ [{2015,"immig",2.767,"senti:ne… ┆ 1            │
│ MISC            ┆ East Ukrainian         ┆ [{2020,"inter",4.563,"senti:po… ┆ 1            │
└─────────────────┴────────────────────────┴─────────────────────────────────┴──────────────┘

In [13]:
# Mentions of "afghan"
search_entity('afghan')

shape: (7, 4)
┌─────────────────┬────────────────────────────────┬────────────────────────────────┬──────────────┐
│ entity_category ┆ entity_content                 ┆ sentences_with_context         ┆ nb_sentences │
│ ---             ┆ ---                            ┆ ---                            ┆ ---          │
│ str             ┆ str                            ┆ list[struct[5]]                ┆ u32          │
╞═════════════════╪════════════════════════════════╪════════════════════════════════╪══════════════╡
│ LOC             ┆ Afghanistan                    ┆ [{2015,"inter",0.528,"senti:mi ┆ 869          │
│                 ┆                                ┆ …                              ┆              │
│ MISC            ┆ Afghan                         ┆ [{2015,"inter",1.541,"senti:ne ┆ 109          │
│                 ┆                                ┆ …                              ┆              │
│ MISC            ┆ Afghans                        ┆ [{2015,"inter",0.625,"senti:mi ┆ 50           │
│                 ┆                                ┆ …                              ┆              │
│ MISC            ┆ inAfghanistan                  ┆ [{2018,"defen",3.277,"senti:ne ┆ 1            │
│                 ┆                                ┆ …                              ┆              │
│ ORG             ┆ Afghan Statistical Institute   ┆ [{2018,"inter",0.246,"senti:ne ┆ 1            │
│                 ┆                                ┆ …                              ┆              │
│ ORG             ┆ Afghanistan Reconstruction     ┆ [{2016,"inter",2.699,"senti:ne ┆ 1            │
│                 ┆ Fun…                           ┆ …                              ┆              │
│ ORG             ┆ Afghanistan Resolute Support   ┆ [{2019,"inter",2.805,"senti:ne ┆ 1            │
│                 ┆ M…                             ┆ …                              ┆              │
└─────────────────┴────────────────────────────────┴────────────────────────────────┴──────────────┘

### Keywords and entities

In [14]:
# Look for a particular keyword associated to a particular entity
def search_keyword_for_entity(keyword, entity):
    pattern_entity = rf'(?i){entity}'
    pattern_keyword = rf'(?i){keyword}'

    return get_results(
        df.filter(
            pl.col('entity_content').str.contains(pattern_entity),
            pl.col('sentence_content_current').str.contains(pattern_keyword),
        )
    )

In [15]:
# Look for mentions of "war" keyword and "afghan" entity
search_keyword_for_entity(r'\bwar\b', 'afghan')

shape: (3, 4)
┌─────────────────┬────────────────┬─────────────────────────────────┬──────────────┐
│ entity_category ┆ entity_content ┆ sentences_with_context          ┆ nb_sentences │
│ ---             ┆ ---            ┆ ---                             ┆ ---          │
│ str             ┆ str            ┆ list[struct[5]]                 ┆ u32          │
╞═════════════════╪════════════════╪═════════════════════════════════╪══════════════╡
│ LOC             ┆ Afghanistan    ┆ [{2015,"inter",0.625,"senti:mi… ┆ 18           │
│ MISC            ┆ Afghans        ┆ [{2015,"inter",0.625,"senti:mi… ┆ 2            │
│ MISC            ┆ Afghan         ┆ [{2018,"inter",1.696,"senti:ne… ┆ 1            │
└─────────────────┴────────────────┴─────────────────────────────────┴──────────────┘

In [16]:
# Look for mentions of "war" keyword and "ukrain" entity
search_keyword_for_entity(r'\bwar\b', 'ukrain')

shape: (5, 4)
┌─────────────────┬─────────────────┬─────────────────────────────────┬──────────────┐
│ entity_category ┆ entity_content  ┆ sentences_with_context          ┆ nb_sentences │
│ ---             ┆ ---             ┆ ---                             ┆ ---          │
│ str             ┆ str             ┆ list[struct[5]]                 ┆ u32          │
╞═════════════════╪═════════════════╪═════════════════════════════════╪══════════════╡
│ LOC             ┆ Ukraine         ┆ [{2015,"inter",4.24,"senti:mix… ┆ 27           │
│ LOC             ┆ Eastern Ukraine ┆ [{2015,"inter",0.169,"senti:ne… ┆ 21           │
│ MISC            ┆ Ukrainian       ┆ [{2016,"inter",0.884,"senti:mi… ┆ 3            │
│ LOC             ┆ Western Ukraine ┆ [{2015,"immig",2.767,"senti:ne… ┆ 1            │
│ MISC            ┆ Ukraine War     ┆ [{2015,"inter",0.594,"senti:mi… ┆ 1            │
└─────────────────┴─────────────────┴─────────────────────────────────┴──────────────┘